/**
 * k6 Summary JSON Parser — Defensive Implementation
 *
 * Reads summary.json generated by k6 and extracts performance metrics.
 * Uses a defensive getMetricValue() helper that handles both nested
 * (metricObj.values[key]) and flat (metricObj[key]) schema variations.
 *
 * Outputs a clean markdown executive summary to GITHUB_STEP_SUMMARY.
 */

const fs = require('fs');
const path = require('path');

// ─── Defensive Metric Extractor ──────────────────────────────────
function getMetricValue(metricObj, key) {
  if (!metricObj) return null;

  // Nested schema: metricObj.values[key] (k6 v0.47+)
  if (metricObj.values && typeof metricObj.values === 'object') {
    if (key in metricObj.values) return metricObj.values[key];
  }

  // Flat schema: metricObj[key] (older k6 versions)
  if (key in metricObj) return metricObj[key];

  // Try type-specific containers
  if (metricObj.type === 'trend' && metricObj.contains === 'time') {
    if (metricObj.values && key in metricObj.values) return metricObj.values[key];
  }

  // Deep search in any nested structure
  for (const prop of Object.values(metricObj)) {
    if (prop && typeof prop === 'object' && key in prop) {
      return prop[key];
    }
  }

  return null;
}

function getMetricRate(metricObj) {
  if (!metricObj) return null;
  // Rate metrics: { type: 'rate', contains: 'default', values: { rate: 0.0 } }
  const rate = getMetricValue(metricObj, 'rate');
  if (rate !== null) return rate;
  // Fallback: check 'passes' and 'fails'
  const passes = getMetricValue(metricObj, 'passes');
  const fails = getMetricValue(metricObj, 'fails');
  if (passes !== null && fails !== null && (passes + fails) > 0) {
    return passes / (passes + fails);
  }
  return null;
}

function formatMs(value) {
  if (value === null || value === undefined) return 'N/A';
  if (typeof value === 'number') return `${value.toFixed(2)}ms`;
  return String(value);
}

function formatRate(value) {
  if (value === null || value === undefined) return 'N/A';
  return `${(value * 100).toFixed(2)}%`;
}

function formatRps(value) {
  if (value === null || value === undefined) return 'N/A';
  return `${value.toFixed(2)} req/sec`;
}

// ─── Main Parser ─────────────────────────────────────────────────
function parseSummary(summaryPath) {
  if (!fs.existsSync(summaryPath)) {
    console.error(`❌ Summary file not found: ${summaryPath}`);
    process.exit(1);
  }

  const raw = fs.readFileSync(summaryPath, 'utf8');
  let summary;
  try {
    summary = JSON.parse(raw);
  } catch (err) {
    console.error(`❌ Failed to parse summary JSON: ${err.message}`);
    process.exit(1);
  }

  // Handle both root-level metrics and nested metrics
  const metrics = summary.metrics || summary;

  // ─── Extract Metrics ────────────────────────────────────────
  const httpReqs = metrics.http_reqs || metrics['http_reqs'] || {};
  const httpDuration = metrics.http_req_duration || metrics['http_req_duration'] || {};
  const httpFailed = metrics.http_req_failed || metrics['http_req_failed'] || {};
  const checks = metrics.checks || {};
  const iterations = metrics.iterations || {};

  // Throughput (RPS)
  const rps = getMetricValue(httpReqs, 'rate') || getMetricValue(iterations, 'rate');
  const totalRequests = getMetricValue(httpReqs, 'count');

  // Response Times
  const avgDuration = getMetricValue(httpDuration, 'avg');
  const minDuration = getMetricValue(httpDuration, 'min');
  const maxDuration = getMetricValue(httpDuration, 'max');
  const medDuration = getMetricValue(httpDuration, 'med');
  const p90Duration = getMetricValue(httpDuration, 'p(90)');
  const p95Duration = getMetricValue(httpDuration, 'p(95)');
  const p99Duration = getMetricValue(httpDuration, 'p(99)');

  // Failure & Check Rates
  const failRate = getMetricRate(httpFailed);
  const checkRate = getMetricRate(checks);

  // Total iterations
  const totalIterations = getMetricValue(iterations, 'count');

  return {
    rps, totalRequests, totalIterations,
    avgDuration, minDuration, maxDuration, medDuration,
    p90Duration, p95Duration, p99Duration,
    failRate, checkRate
  };
}

// ─── Generate Markdown Summary ───────────────────────────────────
function generateSummary(data) {
  const passedThresholds =
    (data.failRate !== null ? data.failRate < 0.05 : true) &&
    (data.p95Duration !== null ? data.p95Duration < 1500 : true);

  const summary = `# 📈 API Load Test Results

## Configuration
| Parameter | Value |
|-----------|-------|
| Virtual Users | 100 |
| Duration | 1 minute |
| Target | BioPolymer AI Screening API |

## Throughput

| Metric | Value |
|--------|-------|
| **Requests/sec (RPS)** | **${formatRps(data.rps)}** |
| Total Requests | ${data.totalRequests !== null ? data.totalRequests : 'N/A'} |
| Total Iterations | ${data.totalIterations !== null ? data.totalIterations : 'N/A'} |

## Response Times

| Metric | Value |
|--------|-------|
| **Average** | **${formatMs(data.avgDuration)}** |
| **Minimum** | **${formatMs(data.minDuration)}** |
| **Maximum** | **${formatMs(data.maxDuration)}** |
| Median (p50) | ${formatMs(data.medDuration)} |
| p(90) | ${formatMs(data.p90Duration)} |
| **p(95)** | **${formatMs(data.p95Duration)}** |
| p(99) | ${formatMs(data.p99Duration)} |

## Reliability

| Metric | Value | Threshold | Status |
|--------|-------|-----------|--------|
| Request Failure Rate | ${formatRate(data.failRate)} | < 5% | ${data.failRate !== null && data.failRate < 0.05 ? '✅ PASS' : '⚠️ CHECK'} |
| Assertion Check Rate | ${formatRate(data.checkRate)} | > 95% | ${data.checkRate !== null && data.checkRate > 0.95 ? '✅ PASS' : '⚠️ CHECK'} |
| p(95) Latency | ${formatMs(data.p95Duration)} | < 1500ms | ${data.p95Duration !== null && data.p95Duration < 1500 ? '✅ PASS' : '⚠️ CHECK'} |

## Overall Result: ${passedThresholds ? '✅ PASSED' : '⚠️ THRESHOLDS EXCEEDED'}

${passedThresholds
  ? '> All performance thresholds met. The API is handling the baseline load of 100 concurrent users successfully.'
  : '> One or more thresholds exceeded. Review response times and error rates for optimization opportunities.'
}

---
*Generated: ${new Date().toISOString()} | Tool: k6 + parseK6Summary.js*
`;

  return summary;
}

// ─── Main ────────────────────────────────────────────────────────
function main() {
  const summaryPath = process.argv[2] || path.resolve(__dirname, 'summary.json');
  console.log(`📊 Parsing k6 summary: ${summaryPath}`);

  const data = parseSummary(summaryPath);

  console.log('\n── Load Test Results ──');
  console.log(`   RPS:          ${formatRps(data.rps)}`);
  console.log(`   Total Reqs:   ${data.totalRequests}`);
  console.log(`   Avg Duration: ${formatMs(data.avgDuration)}`);
  console.log(`   Min Duration: ${formatMs(data.minDuration)}`);
  console.log(`   Max Duration: ${formatMs(data.maxDuration)}`);
  console.log(`   p(95):        ${formatMs(data.p95Duration)}`);
  console.log(`   Fail Rate:    ${formatRate(data.failRate)}`);
  console.log(`   Check Rate:   ${formatRate(data.checkRate)}`);

  const markdown = generateSummary(data);

  // Write to step summary if in CI
  if (process.env.GITHUB_STEP_SUMMARY) {
    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, '\n\n' + markdown, 'utf8');
    console.log('\n✅ Summary written to GITHUB_STEP_SUMMARY');
  }

  // Also write to file
  const outputPath = path.resolve(path.dirname(summaryPath), 'load-test-report.md');
  fs.writeFileSync(outputPath, markdown, 'utf8');
  console.log(`📄 Report saved: ${outputPath}`);
}

main();
